### ISSUE TITLE
how to generate the cluter_transcript ？

### ISSUE THREAD

**Issue by idejie** [ZijiaLewisLu/ICCV21-TASL#6]
1.How to set the variable : https://github.com/ZijiaLewisLu/ICCV21-TASL/blob/6da3eeae59d90cc19b22d1cb4fc70e51c4d784cb/src/utils/cluster_transcript.py#L123

2. All dataset needs the cluter_transcript？

**Comment by ZijiaLewisLu** [comment]
For (1), you can refer to [line](https://github.com/ZijiaLewisLu/ICCV21-TASL/blob/6da3eeae59d90cc19b22d1cb4fc70e51c4d784cb/src/utils/cluster_transcript.py#L89). For example, train_trans_list = [ ['background', 'action1', 'action2' ], ['background, 'action2', 'action3'], ...  ].

For (2), we only use training transcripts.

**Comment by idejie** [comment]
Thanks a lot.

For(2), I mean every dataset needs cluter_transcript?

**Comment by ZijiaLewisLu** [comment]
It is only applied to crosstask dataset.
